// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v2ray.com/v2ray-study/common/serial/typed_message.proto

package serial

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TypedMessage is a serialized proto message along with its type name.
type TypedMessage struct {
	// The name of the message type, retrieved from protobuf API.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Serialized proto message.
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypedMessage) Reset()         { *m = TypedMessage{} }
func (m *TypedMessage) String() string { return proto.CompactTextString(m) }
func (*TypedMessage) ProtoMessage()    {}
func (*TypedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_39a92acb1f0e38be, []int{0}
}

func (m *TypedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypedMessage.Unmarshal(m, b)
}
func (m *TypedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypedMessage.Marshal(b, m, deterministic)
}
func (m *TypedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypedMessage.Merge(m, src)
}
func (m *TypedMessage) XXX_Size() int {
	return xxx_messageInfo_TypedMessage.Size(m)
}
func (m *TypedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TypedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TypedMessage proto.InternalMessageInfo

func (m *TypedMessage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TypedMessage) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*TypedMessage)(nil), "v2ray.core.common.serial.TypedMessage")
}

func init() {
	proto.RegisterFile("v2ray.com/v2ray-study/common/serial/typed_message.proto", fileDescriptor_39a92acb1f0e38be)
}

var fileDescriptor_39a92acb1f0e38be = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x2f, 0x33, 0x2a, 0x4a,
	0xac, 0xd4, 0x4b, 0xce, 0xcf, 0xd5, 0x07, 0xb3, 0x74, 0x8b, 0x4b, 0x4a, 0x53, 0x2a, 0xf5, 0x93,
	0xf3, 0x73, 0x73, 0xf3, 0xf3, 0xf4, 0x8b, 0x53, 0x8b, 0x32, 0x13, 0x73, 0xf4, 0x4b, 0x2a, 0x0b,
	0x52, 0x53, 0xe2, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2,
	0x85, 0x24, 0x60, 0x1a, 0x8b, 0x52, 0xf5, 0x20, 0xaa, 0xf5, 0x20, 0xaa, 0x95, 0x2c, 0xb8, 0x78,
	0x42, 0x40, 0x1a, 0x7c, 0x21, 0xea, 0x85, 0x84, 0xb8, 0x58, 0x40, 0x06, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x10, 0x8e, 0x93, 0x33, 0x97, 0x4c, 0x72, 0x7e, 0xae, 0x1e, 0x2e,
	0x93, 0x03, 0x18, 0xa3, 0xd8, 0x20, 0xac, 0x55, 0x4c, 0x12, 0x61, 0x46, 0x41, 0x89, 0x95, 0x7a,
	0xce, 0x20, 0x45, 0xce, 0x10, 0x45, 0xc1, 0x60, 0xa9, 0x24, 0x36, 0xb0, 0xfb, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x06, 0xd6, 0x67, 0x72, 0xda, 0x00, 0x00, 0x00,
}
